DROP TABLE DEMO1.PERSONA CASCADE CONSTRAINTS;

CREATE TABLE DEMO1.PERSONA
(
  DNI      INTEGER,
  NOMBRES  NVARCHAR2(200),
  CORREO   NVARCHAR2(50),
  FECNAC   NVARCHAR2(10)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
